src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Entity\ActionCounter;
use App\Entity\Citizen;
use App\Entity\CitizenProfession;
use App\Entity\CauseOfDeath;
use App\Entity\Gazette;
use App\Entity\GazetteLogEntry;
use App\Entity\HeroicActionPrototype;
use App\Entity\HeroSkillPrototype;
use App\Entity\ItemPrototype;
use App\Entity\LogEntryTemplate;
use App\Entity\SpecialActionPrototype;
use App\Entity\TownLogEntry;
use App\Entity\Zone;
use App\Response\AjaxResponse;
use App\Service\CitizenHandler;
use App\Service\ConfMaster;
use App\Service\ErrorHelper;
use App\Service\InventoryHandler;
use App\Service\ItemFactory;
use App\Service\JSONRequestParser;
use App\Service\LogTemplateHandler;
use App\Service\PictoHandler;
use App\Service\TimeKeeperService;
use App\Service\TownHandler;
use App\Service\UserHandler;
use App\Structures\ItemRequest;
use App\Structures\TownConf;
use App\Translation\T;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use DateTime;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/",condition="request.isXmlHttpRequest()")
 */
class GameController extends CustomAbstractController implements GameInterfaceController
{
    protected $logTemplateHandler;
    protected TownHandler $town_handler;
    private $user_handler;
    protected PictoHandler $picto_handler;

    public function __construct(EntityManagerInterface $em, TranslatorInterface $translator, LogTemplateHandler $lth, TimeKeeperService $tk, CitizenHandler $ch, UserHandler $uh, TownHandler $th, ConfMaster $conf, PictoHandler $ph, InventoryHandler $ih)
    {
        parent::__construct($conf, $em, $tk, $ch, $ih, $translator);
        $this->logTemplateHandler = $lth;
        $this->user_handler = $uh;
        $this->town_handler = $th;
        $this->picto_handler = $ph;
    }

    protected function getActiveCitizen(): Citizen {
        return $this->entity_manager->getRepository(Citizen::class)->findActiveByUser($this->getUser());
    }

    protected function renderLog( ?int $day, $citizen = null, $zone = null, ?int $type = null, ?int $max = null ): Response {
        $entries = [];
        /** @var TownLogEntry $entity */
        foreach ($this->entity_manager->getRepository(TownLogEntry::class)->findByFilter($this->getActiveCitizen()->getTown(),$day, $citizen, $zone, $type, $max ) as $idx=>$entity) {
            /** @var LogEntryTemplate $template */
            $template = $entity->getLogEntryTemplate();
            if (!$template)
                continue;
            $entityVariables = $entity->getVariables();
            $entries[$idx]['timestamp'] = $entity->getTimestamp();
            $entries[$idx]['class'] = $template->getClass();
            $entries[$idx]['type'] = $template->getType();
            $entries[$idx]['id'] = $entity->getId();
            $entries[$idx]['hidden'] = $entity->getHidden();

            $variableTypes = $template->getVariableTypes();
            $transParams = $this->logTemplateHandler->parseTransParams($variableTypes, $entityVariables);

            try {
                $entries[$idx]['text'] = $this->translator->trans($template->getText(), $transParams, 'game');
            }
            catch (Exception $e) {
                $entries[$idx]['text'] = "null";
            }             
        }

        return $this->render( 'ajax/game/log_content.html.twig', [
            'entries' => $entries,
            'canHideEntry' => $this->getActiveCitizen()->getAlive() && $this->getActiveCitizen()->getProfession()->getHeroic() && $this->user_handler->hasSkill($this->getUser(), 'manipulator'),
        ] );
    }

    protected function parseGazetteLog(GazetteLogEntry $gazetteLogEntry) {
        return $this->parseLog($gazetteLogEntry->getLogEntryTemplate(), $gazetteLogEntry->getVariables());
    }

    protected function parseLog( LogEntryTemplate $template, array $variables ): String {
        $variableTypes = $template->getVariableTypes();
        $transParams = $this->logTemplateHandler->parseTransParams($variableTypes, $variables, true);

        try {
            $text = $this->translator->trans($template->getText(), $transParams, 'game');
        }
        catch (Exception $e) {
            $text = "null";
        }

        return $text;
    }

    /**
     * @Route("jx/game/landing", name="game_landing")
     * @return Response
     */
    public function landing(): Response
    {
        if (!$this->getActiveCitizen()->getAlive())
            return $this->redirect($this->generateUrl('soul_death'));
        elseif ($this->getActiveCitizen()->getProfession()->getName() === CitizenProfession::DEFAULT)
            return $this->redirect($this->generateUrl('game_jobs'));
        elseif (!$this->getActiveCitizen()->getHasSeenGazette())
            return $this->redirect($this->generateUrl('game_newspaper'));
        elseif ($this->getActiveCitizen()->getZone() && !$this->getActiveCitizen()->activeExplorerStats())
            return $this->redirect($this->generateUrl('beyond_dashboard'));
        elseif ($this->getActiveCitizen()->getZone() && $this->getActiveCitizen()->activeExplorerStats())
            return $this->redirect($this->generateUrl('exploration_dashboard'));
        else return $this->redirect($this->generateUrl('town_dashboard'));
    }

    /**
     * @Route("jx/game/raventimes", name="game_newspaper")
     * @return Response
     */
    public function newspaper(): Response {
        file_put_contents("/tmp/dump.txt", "Newspaper !\n");
        if ($this->getActiveCitizen()->getAlive() && $this->getActiveCitizen()->getProfession()->getName() === CitizenProfession::DEFAULT)
            return $this->redirect($this->generateUrl('game_landing'));

        file_put_contents("/tmp/dump.txt", "Job is defined !\n");
        $in_town = $this->getActiveCitizen()->getZone() === null;
        $town = $this->getActiveCitizen()->getTown();
        $day = $town->getDay();
        $death_outside = $death_inside = [];

        $has_living_citizens = false;
        foreach ( $town->getCitizens() as $c )
            if ($c->getAlive()) {
                $has_living_citizens = true;
                break;
            }

        if (!$has_living_citizens)
            return $this->redirect($this->generateUrl('game_landing'));

        /** @var Gazette $gazette */
        $gazette = $town->findGazette( $day );
        if (!$gazette) {
            $gazette = new Gazette();
            $gazette->setTown($town)->setDay($town->getDay());
            $town->addGazette($gazette);
        }

        $survivors = [];
        foreach ($town->getCitizens() as $citizen) {
            if(!$citizen->getAlive()) continue;
            $survivors[] = $citizen;
        }

        foreach ($gazette->getVictims() as $citizen) {
            if($citizen->getAlive()) continue;
            if ($citizen->getCauseOfDeath()->getRef() == CauseOfDeath::NightlyAttack)
                $death_inside[] = $citizen;
            else
                $death_outside[] = $citizen;
        }

        if (count($death_inside) > $gazette->getDeaths()) {
            $gazette->setDeaths(count($death_inside));
        }

        $gazette_logs = $this->entity_manager->getRepository(GazetteLogEntry::class)->findByFilter($gazette, LogEntryTemplate::TypeGazetteTown);
        $text = '';
        $wind = "";
        if (count($gazette_logs) == 0) {
            // No Gazette texts! Let's generate some...
            if ($day == 1) {
                // TODO: Turn into LogEntryTemplate
                $text = "<p>" . $this->translator->trans('Heute Morgen ist kein Artikel erschienen...', [], 'game') . "</p>";
                if ($town->isOpen()){
                    $text .= "<p>" . $this->translator->trans('Die Stadt wird erst starten, wenn sie <strong>%population% Bürger hat</strong>.', ['%population%' => $town->getPopulation()], 'game') . "</p>" . "<a class='help-button'>" . "<div class='tooltip help'>" . $this->translator->trans("Falls sich dieser Zustand auch um Mitternacht noch nicht geändert hat, findet kein Zombieangriff statt. Der Tag wird dann künstlich verlängert.", [], 'global') . "</div>" . $this->translator->trans("Hilfe", [], 'global') . "</a>";
                } else {
                    $text .= $this->translator->trans('Fangt schon mal an zu beten, Bürger - die Zombies werden um Mitternacht angreifen!', [], 'game');
                }
            } else {
                // 1. TOWN
                if($town->getDevastated()){
                    $criteria = [
                        'name' => 'gazetteTownDevastated'
                    ];
                } else {
                    $criteria = [
                        'type'  => LogEntryTemplate::TypeGazetteTown,
                        'class' => LogEntryTemplate::ClassGazetteNoDeaths + (count($death_inside) < 3 ? count($death_inside) : 3),
                    ];
                }

                $applicableEntryTemplates = $this->entity_manager->getRepository(LogEntryTemplate::class)->findBy($criteria);
                shuffle($applicableEntryTemplates);
                /** @var LogEntryTemplate $townTemplate */
                $townTemplate = $applicableEntryTemplates[array_key_first($applicableEntryTemplates)];
                $requirements = $townTemplate->getSecondaryType();
                $variables = [];
                if ($requirements == GazetteLogEntry::RequiresNothing) {
                    $variables = [];
                }
                elseif (intval(floor($requirements / 10)) === 1) {
                    $citizens = $survivors;
                    shuffle($citizens);
                    for ($i = 1; $i <= $requirements - 10; $i++) {
                        $variables['citizen' . $i] = (array_shift($citizens))->getId();
                    }
                }
                elseif (intval(floor($requirements / 10)) === 2) {

templates/ajax/game/town/bank.html.twig
{% extends "ajax/game/town/town.html.twig" %}
{% block title %}{{'Die Bank'|trans({}, 'game')}}{% endblock %}
{% block content %}
    {% set hour = "now"|date("G") %}
    <div class="row">
        <div class="cell rw-12 town-banner town-banner-bank time-{{ hour }} {% if town.isNight %}night{% endif %}"></div>
    </div>

    <div class="help">
        {% trans from 'game' %}
            Hier findest du alle Gegenstände, die gegenwärtig in der Bank aufbewahrt werden. Bei diesen Gegenständen handelt es sich um Spenden der Bürger. Sie sind im Wesentlichen dazu da, Gemeinschaftsgebäude zu bauen und die Stadt gegen die allnächtlichen Zombieattacken zu verteidigen.
        {% endtrans %}
    </div>

    <div class="row-flex wrap town-summary">
        <div class="padded cell rw-4 ellipsis row-header"><img src="{{ asset('build/images/item/item_plate.gif') }}" /> {{'Stadtverteidigung'|trans({}, 'game')}}</div>
        <div class="padded cell rw-8 ellipsis row-detail">{{def}} <img src="{{ asset('build/images/icons/small_def.gif') }}" /> (<span class="link" x-ajax-href="{{ path('town_dashboard') }}">{{'Details ansehen'|trans({}, 'game')}}</span>)</div>
        <div class="padded cell rw-4 ellipsis row-header">{{'Verteidigungsgegenstände'|trans({}, 'game')}}</div>
        <div class="padded cell rw-8 ellipsis row-detail">{{item_defense}} {{'Punkte'|trans({}, 'global')}} ({{item_def_count}} {{'Gegenstände'|trans({}, 'game')}} x {{item_def_factor}} <img src="{{ asset('build/images/icons/small_def.gif') }}" /> ) <a class="help-button"><div class="tooltip help">{{ 'Jeder <strong>Verteidigungsgegenstand</strong>, der sich in der Bank befindet, bringt der Stadt <strong>1 Verteidigungspunkte</strong>.'|trans({},'global')|raw }}</div>{{ 'Hilfe'|trans({},'global') }}</a> </div>
    </div>

    <div class="row-flex wrap">
        <div class="padded cell rw-6 rw-lg-12">
            {% embed "ajax/game/inventory.html.twig" with {'size': rucksack_size, 'items': rucksack.items} %}
                {% block class %}rucksack{% endblock %}
                {% block title %}{% trans from 'game' %}Rucksack{% endtrans %}{% endblock %}
            {% endembed %}

            <button id="drop-all-button" {% if rucksack.items|length == 0 %}disabled{% endif %}><img alt="" src="{{ asset('build/images/item/item_bag.gif') }}"> {% trans from 'game' %}Rucksack in der Bank ausleeren{% endtrans %}</button>

            {% embed "ajax/game/inventory.html.twig" with {'size': 0, 'items': bank, 'bankmode': true} %}
                {% block class %}bank{% endblock %}
                {% block title %}{% endblock %}
            {% endembed %}
        </div>

        <div class="padded cell rw-6 rw-lg-12 hide-sm" style="position: relative; min-height: 180px;">
            <div class="forum-preview-container" style="position: absolute; left: 3px; top: 3px; right: 3px; bottom: 3px">
                <div id="forum-content">
                    <div class="center"><i class="fa fa-spin fa-circle-notch"></i> {{ 'Lade Forum...'|trans({},'game') }}</div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h5>{% trans from 'game' %}Bankregister{% endtrans %}</h5>
        <div class="cell rw-12">
            {% embed "ajax/game/log.html.twig" with {'log_content': log, 'log_source': path('town_bank_log_controller') } %}
            {% endembed %}
        </div>
    </div>
{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        {% embed "scripts/inventory.js.twig" %}{% endembed %};
        {% embed "scripts/log.js.twig" %}{% endembed %}

        handleItems(
            document.querySelectorAll('.rucksack>.item:not(.locked)[x-item-id]'),
            '{{ path('town_bank_item_controller') }}',
            'down', '{{ path('town_bank') }}'
        );

        handleItems(
            document.querySelectorAll('#drop-all-button'),
            '{{ path('town_bank_item_controller') }}',
            'down-all', '{{ path('town_bank') }}'
        );

        handleItems(
            document.querySelectorAll('.bank>.item:not(.locked)[x-item-id]'),
            '{{ path('town_bank_item_controller') }}',
            'up', '{{ path('town_bank') }}'
        );

        $.ajax.background().no_history().load( document.getElementById('forum-content'), '{{ path('forum_previewer_controller', {fid: town.forum.id, sem: constant('App\\Entity\\Thread::SEMANTIC_BANK') })|e('js') }}', false, {}, function() {
            let container = document.querySelector('.forum-preview-container');
            container.scrollTop = container.scrollHeight;
        } );
    </script>
{% endblock %}

templates/ajax/game/town/catapult.html.twig
{% extends "ajax/game/town/town.html.twig" %}
{% block title %}{{'Katapult'|trans({}, 'game')}}{% endblock %}
{% block content %}

    <h1 class="page-head">{{'Katapult'|trans({}, 'game')}}</h1>

    <div class="help">
        <strong>{{ 'Das Katapult ist ein wirklich mächtiges Instrument, um jeden beliebigen Gegenstand zu einer Zone in der Wüste zu schicken.'|trans({},'game') }}</strong>
        {{ 'Praktisch zur Versorgung aus der Ferne.'|trans({},'game') }}
        <p>{{ 'Denke daran, dass das Katapult manchmal sein Ziel verfehlt und den Gegenstand in eine angrenzende Zone befördert...'|trans({},'game')}}</p>
        <p>
            {% if is_catapult_master %}
                <strong>{{'Du wurdest als Verantwortlicher für das Katapult bestimmt!'|trans({},'game')}}</strong>
                {{'Wähle einen Gegenstand aus deinem Inventar und gib die Zielkoordinaten ein.'|trans({},'game')}}
            {% elseif catapult_master is not null %}
                {{'Unser Katapult wird von dem vom Schicksal auserwählten Bürger %citizen% gesteuert. Sollte ihm etwas Schreckliches zustoßen, könnte dann ein neuer Bürger gewählt werden.'|trans({'%citizen%': ('<span class="link" x-ajax-href="' ~ path('town_visit', {id: catapult_master.id}) ~ '"><b>' ~ catapult_master.user.name ~ '</b></span>')},'game')|raw}}
            {% endif %}
        </p>
        {% if catapult_improved %}
            {{ 'Die Aktivierung des Katapults kostet %ap%.'|trans({'%ap%': '<div class="ap">2</div>'},'game')|raw }}
        {% else %}
            {{ 'Die Aktivierung des Katapults kostet %ap% (diese Kosten können durch den Bau eines besseren Katapults gesenkt werden).'|trans({'%ap%': '<div class="ap">4</div>'},'game')|raw }}
        {% endif %}
    </div>

    {% if catapult_master is null %}
        <p>
            <button id="cata_new">{{ 'Einen zufälligen Bürger als Katapult-Bediener auslosen'|trans({},'game') }}</button>
        </p>
    {% endif %}

    {% if is_catapult_master %}
        <div class="row">
            <div class="cell-small rw-10 ro-7 rw-md-14 ro-md-5 rw-sm-24 ro-sm-0">
                <div class="note">
                    <div class="center"><strong>{{ 'Zu verschickender Gegenstand:'|trans({},'game') }}</strong></div>
                    <div><label><select id="cata_what">
                        <option value="-1">-- {{ 'Gegenstand auswählen'|trans({},'game') }} --</option>
                        {% for item in app.user.activeCitizen.inventory.items %}
                            {# @var item \App\Entity\Item #}
                            {% if not item.essential and not item.broken %}
                                <option value="{{ item.id }}">{{ item.prototype.label|trans({},'items') }}</option>
                            {% endif %}
                        {% endfor %}
                    </select></label></div>
                    <div class="row">
                        <div class="padded cell rw-6">
                            <div class="center"><label for="cata_x"><strong>X</strong></label></div>
                            <input id="cata_x" type="number" />
                        </div>
                        <div class="padded cell rw-6">
                            <div class="center"><label for="cata_y"><strong>Y</strong></label></div>
                            <input id="cata_y" type="number" />
                        </div>
                    </div>
                    <div class="row"><div class="padded cell rw-12"><button id="cata_do">{{ 'Gegenstand katapultieren'|trans({},'game') }}</button></div></div>
                </div>
            </div>
        </div>
    {% endif %}

    <div class="row">
        <h5>{% trans from 'game' %}Katapultregister{% endtrans %}</h5>
        <div class="cell rw-12">
            {% embed "ajax/game/log.html.twig" with {'log_content': log, 'log_source': path('town_catapult_log_controller') } %}
            {% endembed %}
        </div>
    </div>

{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        {% embed "scripts/log.js.twig" %}{% endembed %}

        {% if is_catapult_master %}
            $.html.addEventListenerAll('#cata_do', 'click', function () {
                const item = parseInt(document.getElementById('cata_what').value);
                const x = parseInt(document.getElementById('cata_x').value);
                const y = parseInt(document.getElementById('cata_y').value);

                if (item <= 0) {
                    $.html.message('error', '{{ 'Bitte wähle einen Gegenstand.'|trans({},'game') }}');
                    return;
                }
                if (isNaN(x) || isNaN(y)) {
                    $.html.message('error', '{{ 'Bitte gib die Zielkoordinaten ein.'|trans({},'game') }}');
                    return;
                }

                $.ajax.easySend( '{{ path('town_catapult_do_controller') }}', {item: item, x: x, y: y},
                    function () {
                        $.ajax.load(null, '{{ path('town_catapult') }}', true);
                    } );
            });
        {% endif %}

        {% if catapult_master is null %}
            $.html.addEventListenerAll('#cata_new', 'click', function () {
                $.ajax.easySend( '{{ path('town_catapult_assign_controller') }}', {},
                    function () {
                        $.ajax.load(null, '{{ path('town_catapult') }}', true);
                    } );
            });
        {% endif %}
    </script>
{% endblock %}

templates/ajax/game/town/citizen_omniscience.html.twig
{% extends "ajax/game/town/town.html.twig" %}
{% block title %}{{'Die Bürger'|trans({}, 'game')}}{% endblock %}
{% block content %}
    {% set hour = "now"|date("G") %}
    <div class="row">
        <div class="cell rw-12 town-banner town-banner-houses time-{{ hour }} {% if town.isNight %}night{% endif %}"></div>
    </div>

    <ul class="tabs plain">
        <li class="tab">
            <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_citizens') }}">
                {% trans from 'game' %}Bürger{% endtrans %}
            </div>
        </li>
        {% for name,role in votesNeeded %}
            {% if role %}
            <li class="tab">
                <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_citizen_vote', {roleId: role.id}) }}">
                    <img alt="" src="{{ asset('build/images/item/item_bureau.gif') }}" /> {{ role.label|trans({}, 'game') }}
                </div>
            </li>
            {% endif %}
        {% endfor %}

        {% if has_omniscience %}
        <li class="tab selected">
            <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_citizens_omniscience') }}"> <img src="{{ asset('build/images/icons/small_view.gif') }}" alt="" />{{'Allwissenheit'|trans({}, 'game')}}</div>
        </li>
        {% endif %}
    </ul>

    <div class="row-table citizens-list">
        <div class="row header">
            <div class="padded cell rw-4 left rw-md-5">{{ 'Bürger'|trans({},'game') }}</div>
            <div class="padded cell rw-4 rw-md-2 center">{{ 'Truhe'|trans({},'game') }}</div>
            <div class="padded cell rw-2 rw-md-1 center">{{ 'Seele'|trans({},'soul') }}</div>
            <div class="padded cell rw-2 center">{{ 'Aktivität'|trans({},'game') }}</div>
        </div>
        {% for citizen in citizens|sort((a,b) => (a.infos.alive == b.infos.alive) ? ((a.infos.alive) ? a.infos.user.name|lower <=> b.infos.user.name|lower : b.infos.survivedDays <=> a.infos.survivedDays) : b.infos.alive <=> a.infos.alive) %}
            {# @var \App\Entity\Citizen citizen  #}
            {% if citizen.infos.alive %}
            <div class="row {% if citizen.infos == me%} me{% endif %}" x-ajax-href="{{ path('town_visit', {id: citizen.infos.id}) }}">
                <div class="padded cell rw-1 rw-md-2">
                        <img alt="{{ citizen.infos.home.prototype.level }}" src="{{ asset('build/images/home/' ~ citizen.infos.home.prototype.icon ~ '.gif') }}" />
                </div>
                <div class="padded cell rw-3 rw-md-3 small">
                    <span>
                        {% if citizen.infos.banished %}
                            <img alt="" src="{{ asset('build/images/icons/banished.gif') }}" />
                        {% elseif citizen.infos.profession.heroic %}
                            <img alt="" src="{{ asset('build/images/professions/hero.gif') }}" />
                        {% else %}
                            <img alt="" src="{{ asset('build/images/professions/void.gif') }}" />
                        {% endif %}
                        <img alt="{{ citizen.infos.profession.label|trans({},'game') }}" src="{{ asset('build/images/professions/' ~ citizen.infos.profession.icon ~ '.gif') }}" />
                        <b>{{ citizen.infos.user.name }}</b>
                    </span>
                </div>
                <div class="padded cell rw-4 rw-md-2 small">
                    {% if citizen.infos.home.chest.items|length == 0 %}
                        <em>{{ 'Leere Truhe'|trans({},'game') }}</em>
                    {% endif %}
                    {% for item in citizen.infos.home.chest.items %}
                        {# @var \App\Entity\Item item #}
                        <img alt="{{ item.prototype.label|trans({},'items') }}" src="{{ asset('build/images/item/item_' ~ item.prototype.icon ~ '.gif') }}" />
                    {% endfor %}
                </div>
                <div class="padded cell rw-2 rd-md-1 small">
                    {{ citizen.soulPoint }} {{ 'Punkt(e)'|trans({},'game') }}
                </div>
                <div class="padded cell rw-2 small center">
                {% if citizen.omniscienceLevel > 0 %}
                    {% for i in range(1, citizen.omniscienceLevel) %}<img src="{{ asset('build/images/icons/small_new.gif') }}" alt="*" />{% endfor %}
                {% endif %}
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

templates/ajax/game/town/citizen_vote.html.twig
{% extends "ajax/game/town/town.html.twig" %}
{% block title %}{{'Die Bürger'|trans({}, 'game')}}{% endblock %}
{% block content %}
    {% set hour = "now"|date("G") %}
    <div class="row">
        <div class="cell rw-12 town-banner town-banner-houses time-{{ hour }} {% if town.isNight %}night{% endif %}"></div>
    </div>

    <ul class="tabs plain">
        <li class="tab">
            <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_citizens') }}">
                {% trans from 'game' %}Bürger{% endtrans %}
            </div>
        </li>
        {% for name,role in votesNeeded %}
            {% if role %}
            <li class="tab {% if selectedRole.id == role.id %}selected{% endif %}">
                <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_citizen_vote', {roleId: role.id}) }}">
                    <img alt="" src="{{ asset('build/images/item/item_bureau.gif') }}" /> {{ role.label|trans({}, 'game') }}
                </div>
            </li>
            {% endif %}
        {% endfor %}

        {% if has_omniscience %}
        <li class="tab">
            <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_citizens_omniscience') }}"> <img src="{{ asset('build/images/icons/small_view.gif') }}" alt="" />{{'Allwissenheit'|trans({}, 'game')}}</div>
        </li>
        {% endif %}
    </ul>

    <div class="row-table citizens-list">
        <div class="row header">
            <div class="padded cell rw-4 left rw-md-7">{{ 'Bürger'|trans({},'game') }}</div>
            <div class="padded cell rw-8 right">{{ 'Aktionen'|trans({},'ghost') }}</div>
        </div>
        {% for citizen in citizens|sort((a,b) => (a.alive == b.alive) ? ((a.alive) ? a.user.name|lower <=> b.user.name|lower : b.survivedDays <=> a.survivedDays) : b.alive <=> a.alive) %}
            {# @var \App\Entity\Citizen citizen  #}
            {% if citizen.alive %}
            <div class="row {% if citizen == me%} me{% endif %}">
                <div class="padded cell rw-1 rw-md-2">
                        <img alt="{{ citizen.home.prototype.level }}" src="{{ asset('build/images/home/' ~ citizen.home.prototype.icon ~ '.gif') }}" />
                </div>
                <div class="padded cell rw-3 rw-md-6 small">
                    <span>
                        {% if citizen.banished %}
                            <img alt="" src="{{ asset('build/images/icons/banished.gif') }}" />
                        {% elseif citizen.profession.heroic %}
                            <img alt="" src="{{ asset('build/images/professions/hero.gif') }}" />
                        {% else %}
                            <img alt="" src="{{ asset('build/images/professions/void.gif') }}" />
                        {% endif %}
                        <img alt="{{ citizen.profession.label|trans({},'game') }}" src="{{ asset('build/images/professions/' ~ citizen.profession.icon ~ '.gif') }}" />
                        <b>{{ citizen.user.name }}</b>
                    </span>
                </div>
                <div class="padded cell rw-3 ro-5 small right">
                    {% if citizen != me %}
                        {% if vote == null %}
                            <button class="vote" x-citizen-id='{{citizen.id}}'>{{'Abstimmen'|trans({}, 'game')}}</button>
                            <div class="tooltip">
                                {{'Klicke hier, um für diesen Bürger zu stimmen.'|trans({}, 'game')}}
                            </div>
                        {% elseif vote != null and vote.votedCitizen.id == citizen.id %}
                            <img src="{{ asset('build/images/icons/small_action.gif') }}" alt="" />
                            <div class="tooltip">
                                {{'Du hast für diesen Bürger gestimmt.'|trans({}, 'game')}}
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        const send_vote_request = function(citizen_id) {
            if (!confirm('{{ 'Bestätigen?'|trans({},'global')|e('js') }}'))
                return;

            $.ajax.easySend( '{{ path('town_citizens_send_vote') }}', {voted_citizen_id: citizen_id, role_id: {{selectedRole.id}}},
                function () {
                    $.ajax.load(null, '{{ path('town_citizen_vote', {roleId: selectedRole.id}) }}', true);
            } );
        };

        let buttons = document.querySelectorAll('[x-citizen-id]');
        for (let i = 0; i < buttons.length; i++)
            buttons[i].addEventListener('click', function() { send_vote_request( this.getAttribute('x-citizen-id') ); })
    </script>
{% endblock %}